"""
VayuDrishti Indian Airports & Route Matrix
Comprehensive repository of 40+ Indian airports and 100+ strategic civil aviation corridors.
"""

AIRPORTS = {
    "DEL": {"name": "Indira Gandhi International Airport", "city": "Delhi", "state": "Delhi", "region": "Northern", "lat": 28.5562, "lon": 77.1000, "tier": "Metro", "pax_rank": 1},
    "BOM": {"name": "Chhatrapati Shivaji Maharaj International Airport", "city": "Mumbai", "state": "Maharashtra", "region": "Western", "lat": 19.0896, "lon": 72.8656, "tier": "Metro", "pax_rank": 2},
    "BLR": {"name": "Kempegowda International Airport", "city": "Bengaluru", "state": "Karnataka", "region": "Southern", "lat": 13.1986, "lon": 77.7066, "tier": "Metro", "pax_rank": 3},
    "HYD": {"name": "Rajiv Gandhi International Airport", "city": "Hyderabad", "state": "Telangana", "region": "Southern", "lat": 17.2403, "lon": 78.4294, "tier": "Metro", "pax_rank": 4},
    "CCU": {"name": "Netaji Subhash Chandra Bose International Airport", "city": "Kolkata", "state": "West Bengal", "region": "Eastern", "lat": 22.6547, "lon": 88.4467, "tier": "Metro", "pax_rank": 5},
    "MAA": {"name": "Chennai International Airport", "city": "Chennai", "state": "Tamil Nadu", "region": "Southern", "lat": 12.9941, "lon": 80.1709, "tier": "Metro", "pax_rank": 6},
    "AMD": {"name": "Sardar Vallabhbhai Patel International Airport", "city": "Ahmedabad", "state": "Gujarat", "region": "Western", "lat": 23.0772, "lon": 72.6347, "tier": "Tier-2", "pax_rank": 7},
    "PNQ": {"name": "Pune Airport", "city": "Pune", "state": "Maharashtra", "region": "Western", "lat": 18.5822, "lon": 73.9197, "tier": "Tier-2", "pax_rank": 8},
    "GOI": {"name": "Dabolim / Manohar International Airport", "city": "Goa", "state": "Goa", "region": "Western", "lat": 15.3808, "lon": 73.8314, "tier": "Tier-2", "pax_rank": 9},
    "JAI": {"name": "Jaipur International Airport", "city": "Jaipur", "state": "Rajasthan", "region": "Northern", "lat": 26.8242, "lon": 75.8122, "tier": "Tier-2", "pax_rank": 10},
    "LKO": {"name": "Chaudhary Charan Singh International Airport", "city": "Lucknow", "state": "Uttar Pradesh", "region": "Northern", "lat": 26.7606, "lon": 80.8893, "tier": "Tier-2", "pax_rank": 11},
    "PAT": {"name": "Jay Prakash Narayan Airport", "city": "Patna", "state": "Bihar", "region": "Eastern", "lat": 25.5913, "lon": 85.0880, "tier": "Tier-2", "pax_rank": 12},
    "GAU": {"name": "Lokpriya Gopinath Bordoloi International Airport", "city": "Guwahati", "state": "Assam", "region": "North-Eastern", "lat": 26.1061, "lon": 91.5859, "tier": "Tier-2", "pax_rank": 13},
    "COK": {"name": "Cochin International Airport", "city": "Kochi", "state": "Kerala", "region": "Southern", "lat": 10.1520, "lon": 76.4019, "tier": "Tier-2", "pax_rank": 14},
    "BBI": {"name": "Biju Patnaik International Airport", "city": "Bhubaneswar", "state": "Odisha", "region": "Eastern", "lat": 20.2444, "lon": 85.8178, "tier": "Tier-2", "pax_rank": 15},
    "IXR": {"name": "Birsa Munda Airport", "city": "Ranchi", "state": "Jharkhand", "region": "Eastern", "lat": 23.3143, "lon": 85.3217, "tier": "Tier-2", "pax_rank": 16},
    "VNS": {"name": "Lal Bahadur Shastri International Airport", "city": "Varanasi", "state": "Uttar Pradesh", "region": "Northern", "lat": 25.4524, "lon": 82.8590, "tier": "Tier-2", "pax_rank": 17},
    "IXC": {"name": "Shaheed Bhagat Singh International Airport", "city": "Chandigarh", "state": "Punjab/Chandigarh", "region": "Northern", "lat": 30.6735, "lon": 76.7885, "tier": "Tier-2", "pax_rank": 18},
    "IDR": {"name": "Devi Ahilya Bai Holkar Airport", "city": "Indore", "state": "Madhya Pradesh", "region": "Central", "lat": 22.7217, "lon": 75.8011, "tier": "Tier-2", "pax_rank": 19},
    "SXR": {"name": "Sheikh ul-Alam International Airport", "city": "Srinagar", "state": "Jammu and Kashmir", "region": "Northern", "lat": 33.9871, "lon": 74.7741, "tier": "Hill_Island", "pax_rank": 20},
    "IXL": {"name": "Kushok Bakula Rimpochee Airport", "city": "Leh", "state": "Ladakh", "region": "Northern", "lat": 34.1359, "lon": 77.5465, "tier": "Hill_Island", "pax_rank": 21},
    "IXZ": {"name": "Veer Savarkar International Airport", "city": "Port Blair", "state": "Andaman and Nicobar", "region": "Southern", "lat": 11.6410, "lon": 92.7297, "tier": "Hill_Island", "pax_rank": 22},
    "DBG": {"name": "Darbhanga Airport", "city": "Darbhanga", "state": "Bihar", "region": "Eastern", "lat": 26.1950, "lon": 85.9142, "tier": "UDAN_RCS", "pax_rank": 23},
    "IXD": {"name": "Prayagraj Airport", "city": "Prayagraj", "state": "Uttar Pradesh", "region": "Northern", "lat": 25.4402, "lon": 81.7345, "tier": "UDAN_RCS", "pax_rank": 24},
    "KNU": {"name": "Kanpur Airport", "city": "Kanpur", "state": "Uttar Pradesh", "region": "Northern", "lat": 26.4408, "lon": 80.4124, "tier": "UDAN_RCS", "pax_rank": 25},
    "IMF": {"name": "Bir Tikendrajit International Airport", "city": "Imphal", "state": "Manipur", "region": "North-Eastern", "lat": 24.7600, "lon": 93.8967, "tier": "UDAN_RCS", "pax_rank": 26},
    "SHL": {"name": "Shillong Airport (Umroi)", "city": "Shillong", "state": "Meghalaya", "region": "North-Eastern", "lat": 25.7036, "lon": 91.9789, "tier": "UDAN_RCS", "pax_rank": 27},
    "DIB": {"name": "Dibrugarh Airport", "city": "Dibrugarh", "state": "Assam", "region": "North-Eastern", "lat": 27.4839, "lon": 95.0175, "tier": "UDAN_RCS", "pax_rank": 28},
    "VTZ": {"name": "Visakhapatnam International Airport", "city": "Visakhapatnam", "state": "Andhra Pradesh", "region": "Southern", "lat": 17.7212, "lon": 83.2245, "tier": "Tier-2", "pax_rank": 29},
    "ATQ": {"name": "Sri Guru Ram Dass Jee International Airport", "city": "Amritsar", "state": "Punjab", "region": "Northern", "lat": 31.7096, "lon": 74.7973, "tier": "Tier-2", "pax_rank": 30}
}

# 100+ Standard Representative Route Network Matrix
ROUTES = [
    # Metro-to-Metro Trunk Routes (Highest Volume)
    {"origin": "DEL", "destination": "BOM", "category": "METRO_METRO", "distance_km": 1148, "base_pax_monthly": 620000},
    {"origin": "BOM", "destination": "DEL", "category": "METRO_METRO", "distance_km": 1148, "base_pax_monthly": 615000},
    {"origin": "BLR", "destination": "DEL", "category": "METRO_METRO", "distance_km": 1740, "base_pax_monthly": 480000},
    {"origin": "DEL", "destination": "BLR", "category": "METRO_METRO", "distance_km": 1740, "base_pax_monthly": 475000},
    {"origin": "BOM", "destination": "BLR", "category": "METRO_METRO", "distance_km": 842,  "base_pax_monthly": 440000},
    {"origin": "BLR", "destination": "BOM", "category": "METRO_METRO", "distance_km": 842,  "base_pax_monthly": 435000},
    {"origin": "DEL", "destination": "HYD", "category": "METRO_METRO", "distance_km": 1253, "base_pax_monthly": 380000},
    {"origin": "HYD", "destination": "DEL", "category": "METRO_METRO", "distance_km": 1253, "base_pax_monthly": 375000},
    {"origin": "DEL", "destination": "CCU", "category": "METRO_METRO", "distance_km": 1305, "base_pax_monthly": 350000},
    {"origin": "CCU", "destination": "DEL", "category": "METRO_METRO", "distance_km": 1305, "base_pax_monthly": 345000},
    {"origin": "MAA", "destination": "DEL", "category": "METRO_METRO", "distance_km": 1760, "base_pax_monthly": 330000},
    {"origin": "DEL", "destination": "MAA", "category": "METRO_METRO", "distance_km": 1760, "base_pax_monthly": 325000},
    {"origin": "BOM", "destination": "CCU", "category": "METRO_METRO", "distance_km": 1654, "base_pax_monthly": 290000},
    {"origin": "CCU", "destination": "BOM", "category": "METRO_METRO", "distance_km": 1654, "base_pax_monthly": 285000},
    {"origin": "BOM", "destination": "MAA", "category": "METRO_METRO", "distance_km": 1033, "base_pax_monthly": 260000},
    {"origin": "MAA", "destination": "BOM", "category": "METRO_METRO", "distance_km": 1033, "base_pax_monthly": 255000},
    {"origin": "BOM", "destination": "HYD", "category": "METRO_METRO", "distance_km": 623,  "base_pax_monthly": 240000},
    {"origin": "HYD", "destination": "BOM", "category": "METRO_METRO", "distance_km": 623,  "base_pax_monthly": 235000},
    {"origin": "BLR", "destination": "HYD", "category": "METRO_METRO", "distance_km": 500,  "base_pax_monthly": 220000},
    {"origin": "HYD", "destination": "BLR", "category": "METRO_METRO", "distance_km": 500,  "base_pax_monthly": 215000},
    {"origin": "BLR", "destination": "CCU", "category": "METRO_METRO", "distance_km": 1560, "base_pax_monthly": 210000},
    {"origin": "CCU", "destination": "BLR", "category": "METRO_METRO", "distance_km": 1560, "base_pax_monthly": 205000},
    {"origin": "BLR", "destination": "MAA", "category": "METRO_METRO", "distance_km": 290,  "base_pax_monthly": 180000},
    {"origin": "MAA", "destination": "BLR", "category": "METRO_METRO", "distance_km": 290,  "base_pax_monthly": 175000},

    # Metro-to-Tier-2 Key Corridors
    {"origin": "DEL", "destination": "PAT", "category": "METRO_TIER2", "distance_km": 850,  "base_pax_monthly": 220000},
    {"origin": "PAT", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 850,  "base_pax_monthly": 215000},
    {"origin": "DEL", "destination": "LKO", "category": "METRO_TIER2", "distance_km": 430,  "base_pax_monthly": 195000},
    {"origin": "LKO", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 430,  "base_pax_monthly": 190000},
    {"origin": "DEL", "destination": "AMD", "category": "METRO_TIER2", "distance_km": 775,  "base_pax_monthly": 210000},
    {"origin": "AMD", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 775,  "base_pax_monthly": 205000},
    {"origin": "BOM", "destination": "AMD", "category": "METRO_TIER2", "distance_km": 440,  "base_pax_monthly": 190000},
    {"origin": "AMD", "destination": "BOM", "category": "METRO_TIER2", "distance_km": 440,  "base_pax_monthly": 185000},
    {"origin": "DEL", "destination": "PNQ", "category": "METRO_TIER2", "distance_km": 1170, "base_pax_monthly": 225000},
    {"origin": "PNQ", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 1170, "base_pax_monthly": 220000},
    {"origin": "DEL", "destination": "GOI", "category": "METRO_TIER2", "distance_km": 1500, "base_pax_monthly": 230000},
    {"origin": "GOI", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 1500, "base_pax_monthly": 225000},
    {"origin": "BOM", "destination": "GOI", "category": "METRO_TIER2", "distance_km": 435,  "base_pax_monthly": 240000},
    {"origin": "GOI", "destination": "BOM", "category": "METRO_TIER2", "distance_km": 435,  "base_pax_monthly": 235000},
    {"origin": "BLR", "destination": "GOI", "category": "METRO_TIER2", "distance_km": 480,  "base_pax_monthly": 170000},
    {"origin": "DEL", "destination": "GAU", "category": "METRO_TIER2", "distance_km": 1460, "base_pax_monthly": 180000},
    {"origin": "GAU", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 1460, "base_pax_monthly": 175000},
    {"origin": "CCU", "destination": "GAU", "category": "METRO_TIER2", "distance_km": 510,  "base_pax_monthly": 160000},
    {"origin": "DEL", "destination": "VNS", "category": "METRO_TIER2", "distance_km": 670,  "base_pax_monthly": 165000},
    {"origin": "VNS", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 670,  "base_pax_monthly": 160000},
    {"origin": "BOM", "destination": "VNS", "category": "METRO_TIER2", "distance_km": 1250, "base_pax_monthly": 140000},
    {"origin": "DEL", "destination": "BBI", "category": "METRO_TIER2", "distance_km": 1270, "base_pax_monthly": 155000},
    {"origin": "BBI", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 1270, "base_pax_monthly": 150000},
    {"origin": "DEL", "destination": "COK", "category": "METRO_TIER2", "distance_km": 2050, "base_pax_monthly": 175000},
    {"origin": "COK", "destination": "DEL", "category": "METRO_TIER2", "distance_km": 2050, "base_pax_monthly": 170000},
    {"origin": "BOM", "destination": "COK", "category": "METRO_TIER2", "distance_km": 1070, "base_pax_monthly": 160000},
    {"origin": "DEL", "destination": "IXR", "category": "METRO_TIER2", "distance_km": 1000, "base_pax_monthly": 135000},
    {"origin": "DEL", "destination": "IXC", "category": "METRO_TIER2", "distance_km": 240,  "base_pax_monthly": 120000},
    {"origin": "DEL", "destination": "IDR", "category": "METRO_TIER2", "distance_km": 660,  "base_pax_monthly": 130000},
    {"origin": "BOM", "destination": "IDR", "category": "METRO_TIER2", "distance_km": 510,  "base_pax_monthly": 125000},
    {"origin": "DEL", "destination": "JAI", "category": "METRO_TIER2", "distance_km": 235,  "base_pax_monthly": 110000},
    {"origin": "BOM", "destination": "PAT", "category": "METRO_TIER2", "distance_km": 1460, "base_pax_monthly": 150000},

    # Hill & Island Strategic Corridors (High Volatility / Seasonal Spikes)
    {"origin": "DEL", "destination": "IXL", "category": "HILL_ISLAND", "distance_km": 620,  "base_pax_monthly": 85000},
    {"origin": "IXL", "destination": "DEL", "category": "HILL_ISLAND", "distance_km": 620,  "base_pax_monthly": 80000},
    {"origin": "DEL", "destination": "SXR", "category": "HILL_ISLAND", "distance_km": 645,  "base_pax_monthly": 165000},
    {"origin": "SXR", "destination": "DEL", "category": "HILL_ISLAND", "distance_km": 645,  "base_pax_monthly": 160000},
    {"origin": "BOM", "destination": "SXR", "category": "HILL_ISLAND", "distance_km": 1670, "base_pax_monthly": 75000},
    {"origin": "CCU", "destination": "IXZ", "category": "HILL_ISLAND", "distance_km": 1305, "base_pax_monthly": 95000},
    {"origin": "IXZ", "destination": "CCU", "category": "HILL_ISLAND", "distance_km": 1305, "base_pax_monthly": 90000},
    {"origin": "MAA", "destination": "IXZ", "category": "HILL_ISLAND", "distance_km": 1365, "base_pax_monthly": 85000},
    {"origin": "IXZ", "destination": "MAA", "category": "HILL_ISLAND", "distance_km": 1365, "base_pax_monthly": 80000},
    {"origin": "DEL", "destination": "IXZ", "category": "HILL_ISLAND", "distance_km": 2480, "base_pax_monthly": 70000},

    # UDAN RCS Regional Connectivity Corridors (Subsidized & Critical Connectivity)
    {"origin": "DEL", "destination": "DBG", "category": "UDAN_RCS", "distance_km": 880,  "base_pax_monthly": 65000},
    {"origin": "DBG", "destination": "DEL", "category": "UDAN_RCS", "distance_km": 880,  "base_pax_monthly": 62000},
    {"origin": "BOM", "destination": "DBG", "category": "UDAN_RCS", "distance_km": 1490, "base_pax_monthly": 45000},
    {"origin": "DEL", "destination": "IXD", "category": "UDAN_RCS", "distance_km": 570,  "base_pax_monthly": 55000},
    {"origin": "BOM", "destination": "IXD", "category": "UDAN_RCS", "distance_km": 1160, "base_pax_monthly": 42000},
    {"origin": "DEL", "destination": "KNU", "category": "UDAN_RCS", "distance_km": 390,  "base_pax_monthly": 38000},
    {"origin": "GAU", "destination": "IMF", "category": "UDAN_RCS", "distance_km": 270,  "base_pax_monthly": 35000},
    {"origin": "IMF", "destination": "GAU", "category": "UDAN_RCS", "distance_km": 270,  "base_pax_monthly": 34000},
    {"origin": "GAU", "destination": "DIB", "category": "UDAN_RCS", "distance_km": 380,  "base_pax_monthly": 32000},
    {"origin": "CCU", "destination": "SHL", "category": "UDAN_RCS", "distance_km": 490,  "base_pax_monthly": 28000}
]
